# Generated by Django 3.2.6 on 2021-08-25 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20210823_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='last_act',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
